management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    # needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      # defaultZone: http://fiax-springcloud-eureka-1:8761/eureka/, http://fiax-springcloud-eureka-2:8762/eureka/
      defaultZone: ${EUREKA_SERVICE_URL:http://fiax-springcloud-eureka-1:8761}/eureka/
logging:
  file: logs/${spring.application.name}.log